
DROP TABLE IF EXISTS order_ CASCADE;
DROP SEQUENCE IF EXISTS seq1 CASCADE;
CREATE SEQUENCE seq1 START WITH 1;

CREATE TABLE order_ (
   id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
   orderNumber VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS orderRow;
DROP SEQUENCE IF EXISTS seq2 CASCADE;
CREATE SEQUENCE seq2 START WITH 1;

CREATE TABLE orderRow (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq2'),
    orderId BIGINT NOT NULL REFERENCES order_ (id) ON DELETE CASCADE,
    itemName VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    price INTEGER NOT NULL

);
