
DROP TABLE IF EXISTS order_;

DROP SEQUENCE IF EXISTS seq1 CASCADE;

CREATE SEQUENCE seq1 START WITH 1;

CREATE TABLE order_ (
   id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
   orderNumber VARCHAR(255) NOT NULL,
   orderRows VARCHAR(255)
);
